---
title: "Codebook"
author: "Michael Baldassaro"
date: "October 28, 2017"
output: html_document
---

# Codebook

### Abstract
From the University of Califronia Irvine Human Activity Recognition (UCI HAR) database, the average of mean and standard deviation for mean and frequency data built from the recordings of 30 subjects performing activities of daily living (ADL) while carrying a waist-mounted smartphone with embedded inertial sensors.

## About The Data

See [Human Activity Recognition Using Smartphones Data Set] (http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones) for original research design and methodology. The summary data in the tidyAnalysis.csv file represents the average of the mean and standard deviation of the time and frequency variables grouped by subject and activity from the original dataset.    

[Source Data] (https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip)

Source Citation: Lichman, M. (2013). UCI Machine Learning Repository <http://archive.ics.uci.edu/ml>. Irvine, CA: University of California, School of Information and Computer Science. 

Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. A Public Domain Dataset for Human Activity Recognition Using Smartphones. 21th European Symposium on Artificial Neural Networks, Computational Intelligence and Machine Learning, ESANN 2013. Bruges, Belgium 24-26 April 2013.

## Variables
For each record in the dataset it is provided: 
- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.
- Triaxial Angular velocity from the gyroscope. 
- Its activity label (walking, walking upstairs, walking downstairs, sitting, standing, laying). 
- An identifier of the subject who carried out the experiment (1-30).
- An 66-feature vector with mean() and std() for time and frequency domain variables grouped by actvity and subject. 
- Note: meanFreq() and angle() measurements that reference mean and frequency values have been excluded 

Mean: Mean value
SD: Standard deviation

Variable                          | Description 
--------------------------------- | ------------------------------------------------------------------------------------------------------
[,1] activity                     | <factor> 6 levels: walking, walking upstairs, walking downstairs, sitting, standing, laying
[,2] subject                      | <int> range of 1-30 representing each volunteer 
[,3] timeBodyAccMeanX             | <num> average time of acceleration signal by body in the X direction             
[,4] timeBodyAccMeanY             | <num> average time of acceleration signal by body in the Y direction 
[,5] timeBodyAccMeanZ             | <num> average time of acceleration signal by body in the Z direction 
[,6] timeGravityAccMeanX          | <num> average time of acceleration signal by gravity in the X direction        
[,7] timeGravityAccMeanY          | <num> average time of acceleration signal by gravity in the Y direction   
[,8] timeGravityAccMeanZ          | <num> average time of acceleration signal by gravity in the Z direction   
[,9] timeBodyAccJerkMeanX         | <num> average time of linear acceleration (jerk signal) by body in the X direction   
[,10] timeBodyAccJerkMeanY        | <num> average time of linear acceleration (jerk signal) by body in the Y direction 
[,11] timeBodyAccJerkMeanZ        | <num> average time of linear acceleration (jerk signal) by body in the Z direction 
[,12] timeBodyGyroMeanX           | <num> average time of angular velocity by body in the X direction            
[,13] timeBodyGyroMeanY           | <num> average time of angular velocity by body in the Y direction          
[,14] timeBodyGyroMeanZ           | <num> average time of angular velocity by body in the Z direction          
[,15] timeBodyGyroJerkMeanX       | <num> average time of angular velocity by body (jerk signal) in the X direction
[,16] timeBodyGyroJerkMeanY       | <num> average time of angular velocity by body (jerk signal) in the Y direction 
[,17] timeBodyGyroJerkMeanZ       | <num> average time of angular velocity by body (jerk signal) in the Z direction 
[,18] timeBodyAccMagMean          | <num> average magnitude of accelration signal by body using the Euclidean norm     
[,19] timeGravityAccMagMean       | <num> average magnitude of acceleration signal by gravity using the Euclidean norm 
[,20] timeBodyAccJerkMagMean      | <num> average magnitude of linear acceleration (jerk signal) by body using Euclidean norm         
[,21] timeBodyGyroMagMean         | <num> average magnitude of angular velocity by body using Euclidean norm            
[,22] timeBodyGyroJerkMagMean     | <num> average magnitude of angular velocity by body (jerk signal) using Euclidean norm          
[,23] freqBodyAccMeanX            | <num> average frequency of acceleration signal by body in the X direction using FFT 
[,24] freqBodyAccMeanY            | <num> average frequency of acceleration signal by body in the Y direction using FFT  
[,25] freqBodyAccMeanZ            | <num> average frequency of acceleration signal by body in the Z direction using FFT  
[,26] freqBodyAccJerkMeanX        | <num> average frequency of linear acceleration (jerk signal) by body in the X direction using FFT
[,27] freqBodyAccJerkMeanY        | <num> average frequency of linear acceleration (jerk signal) by body in the Y direction using FFT    
[,28] freqBodyAccJerkMeanZ        | <num> average frequency of linear acceleration (jerk signal) by body in the Z direction using FFT    
[,29] freqBodyGyroMeanX           | <num> average frequency of angular velocity by body in the X direction using FFT     
[,30] freqBodyGyroMeanY           | <num> average frequency of angular velocity by body in the Y direction using FFT  
[,31] freqBodyGyroMeanZ           | <num> average frequency of angular velocity by body in the Z direction using FFT   
[,32] freqBodyAccMagMean          | <num> average frequency of magnitude of accelration signal by body using FFT            
[,33] freqBodyBodyAccJerkMagMean  | <num> average frequency of magnitude of linear acceleration (jerk signal) by body using FFT        
[,34] freqBodyBodyGyroMagMean     | <num> average frequency of magnitude of angular velocity by body using FFT       
[,35] freqBodyBodyGyroJerkMagMean | <num> average frequency of magnitude of angular velocity by body (jerk signal) using FFT       
[,36] timeBodyAccSDX              | <num> average standard deviation of time of acceleration signal by body in the X direction 
[,37] timeBodyAccSDY              | <num> average standard deviation of time of acceleration signal by body in the Y direction 
[,38] timeBodyAccSDZ              | <num> average standard deviation of time of acceleration signal by body in the Z direction 
[,39] timeGravityAccSDX           | <num> average standard deviation of time of acceleration signal by gravity in the X direction 
[,40] timeGravityAccSDY           | <num> average standard deviation of time of acceleration signal by gravity in the Y direction 
[,41] timeGravityAccSDZ           | <num> average standard deviation of time of acceleration signal by gravity in the Z direction 
[,42] timeBodyAccJerkSDX          | <num> average standard deviation of time of linear acceleration (jerk signal) by body in X direction   
[,43] timeBodyAccJerkSDY          | <num> average standard deviation of time of linear acceleration (jerk signal) by body in Y direction   
[,44] timeBodyAccJerkSDZ          | <num> average standard deviation of time of linear acceleration (jerk signal) by body in Z direction 
[,45] timeBodyGyroSDX             | <num> average standard deviation of time of angular velocity by body in the X direction  
[,46] timeBodyGyroSDY             | <num> average standard deviation of time of angular velocity by body in the Y direction 
[,47] timeBodyGyroSDZ             | <num> average standard deviation of time of angular velocity by body in the Z direction 
[,48] timeBodyGyroJerkSDX         | <num> average standard deviation of time of angular velocity by body (jerk signal) in the X direction
[,49] timeBodyGyroJerkSDY         | <num> average standard deviation of time of angular velocity by body (jerk signal) in the Y direction
[,50] timeBodyGyroJerkSDZ         | <num> average standard deviation of time of angular velocity by body (jerk signal) in the Z direction
[,51] timeBodyAccMagSD            | <num> average standard deviation of magnitude of accelration signal by body using Euclidean norm 
[,52] timeGravityAccMagSD         | <num> average standard deviation of magnitude of acceleration signal by gravity using Euclidean norm   
[,53] timeBodyAccJerkMagSD        | <num> average standard deviation of magnitude of linear acceleration (jerk signal) by body using Euclidean norm 
[,54] timeBodyGyroMagSD           | <num> average standard deviation of magnitude of angular velocity by body using Euclidean norm      
[,55] timeBodyGyroJerkMagSD       | <num> average standard deviation of magnitude of angular velocity by body (jerk signal) using Euclidean norm 
[,56] freqBodyAccSDX              | <num> average standard deviation of frequency of acceleration signal by body in X direction using FFT  
[,57] freqBodyAccSDY              | <num> average standard deviation of frequency of acceleration signal by body in Y direction using FFT  
[,58] freqBodyAccSDZ              | <num> average standard deviation of frequency of acceleration signal by body in Z direction using FFT  
[,59] freqBodyAccJerkSDX          | <num> average standard deviation of frequency of linear acceleration (jerk signal) by body in X direction using FFT  
[,60] freqBodyAccJerkSDY          | <num> average standard deviation of frequency of linear acceleration (jerk signal) by body in Y direction using FFT
[,61] freqBodyAccJerkSDZ          | <num> average standard deviation of frequency of linear acceleration (jerk signal) by body in Z direction using FFT
[,62] freqBodyGyroSDX             | <num> average standard deviation of frequency of angular velocity by body in the X direction using FFT 
[,63] freqBodyGyroSDY             | <num> average standard deviation of frequency of angular velocity by body in the Y direction using FFT 
[,64] freqBodyGyroSDZ             | <num> average standard deviation of frequency of angular velocity by body in the Z direction using FFT 
[,65] freqBodyAccMagSD            | <num> average standard deviation of frequency of magnitude of accelration signal by body using FFT 
[,66] freqBodyBodyAccJerkMagSD    | <num> average standard deviation of frequency of magnitude of linear acceleration (jerk signal) by body using FFT
[,67] freqBodyBodyGyroMagSD       | <num> average standard deviation of frequency of magnitude of angular velocity by body using FFT 
[,68] freqBodyBodyGyroJerkMagSD   | <num> average standard deviation of frequency of magnitude of angular velocity by body (jerk signal) using FFT  


## Transformations (Data Analysis) 
The original dataset contained seven files that were processed to make a tidyAnalysis.csv file:

* 'features.txt': List of all features.
* 'train/subject_train.txt': Identifiers for activity performers
* 'train/X_train.txt': Training set.
* 'train/y_train.txt': Training labels.
* 'test/subject_test.txt': Identifiers for activity performers
* 'test/X_test.txt': Test set.
* 'test/y_test.txt': Test labels.

Training data (subject_train, X_train, Y_train) and Test data (subject_test, X_test, y_test) were merged to create a full dataset containing all training and test data. Variable names (features) were added as headers to X_train and X_test data.  

From the full dataset, a subset of data containing variables for subject, activity, mean, and standard deviation values was extracted. Activity lables were recoded using values contained in the 'activity_labels.txt' file. Original variable names were cleaned and made descriptive (e.g. "f" was changed to freq, "t" was changed to time) to improve readability.

The average of each mean and standard deviation variable - grouped by activity and subject - was performed on the subsetted data to produce the tidyAnalysis.csv dataset. The tidyAnalysis.csv dataset contains provides the average of mean and standard deviation variables for each activity (6 activities) performed by each subject (30 subjects). The resulting dataset contains 180 observations, an average value for each activity performed by each subject.       
